import StoreProvide from "./StoreProvider";
import "bootstrap/dist/css/bootstrap.min.css";
import BootstrapLoader from "./components/Bootstrap";
import "@/app/styles/globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Suspense } from "react";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import SuspenseLoader from "./utils/SuspenseLoader";
import ReactQueryProvider from "./utils/QueryProvider";
import SettingsLoader from "./utils/SettingsLoader";
import { getStudentAuthPages } from "./features/student/auth/authService";
import { getSettings } from "./features/settings/settingService";
export const metadata = {
  title: "lms-Shams",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const language = "en";
  const authPagesResponse = await getStudentAuthPages(language);
  const settingsResponse = await getSettings(language);

  const authPages = authPagesResponse?.data?.result || null;
  const settings =
    settingsResponse?.data?.data || settingsResponse?.data || null;
  return (
    <html lang="en">
      <body>
        <StoreProvide>
          <Suspense fallback={<SuspenseLoader />}>
            <SettingsLoader authPages={authPages} settings={settings} />
            <Header />
            {children}
            <Footer />
          </Suspense>
        </StoreProvide>

        <BootstrapLoader />
        <div style={{ position: "absolute" }}>
          <ToastContainer position="top-right" autoClose={3000} />
        </div>
      </body>
    </html>
  );
}
